### ISSUE TITLE
Include GitHub repo in `pyproject.toml`

### ISSUE THREAD

**Issue by philiporlando** [philiporlando/fgdb_to_gpkg#27]
@brandones has informed me that this package does not include a GitHub link, which makes it difficult for end users to report bugs and request new features. 

I'm proposing that the `pyproject.toml` be modified to include a repo and homepage:

```toml
[project]
name = "fgdb-to-gpkg"
version = "0.2.2"
description = "A lightweight Python package that converts Esri File GeoDataBases into OGC GeoPackages"
readme = "README.md"
authors = [{name = "Philip Orlando", email = "phlp.orlando@gmail.com"}]
homepage = "https://github.com/philiporlando/fgdb_to_gpkg"
repository = "https://github.com/philiporlando/fgdb_to_gpkg"
```
